services:
  - type: web
    name: prosperojus-bot
    env: python
    pythonVersion: 3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    plan: free  # ou starter, dependendo do plano desejado
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ZAPI_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false

  - type: worker
    name: prosperojus-sheets-worker
    env: python
    pythonVersion: 3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python agendador.py"
    autoDeploy: true
    envVars:
      - key: GOOGLE_SHEETS_CREDENTIALS_JSON
        sync: false
      - key: PLANILHA_ID
        sync: false
